/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5979316c-1fd9-409a-9219-8315f3aa5900",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_U8JtoEJjE",
    "aws_user_pools_web_client_id": "12jubv5n6frll3knujir3fcf0j",
    "oauth": {}
};


export default awsmobile;
